[phases.setup]
aptPkgs = ["python3.11", "python3.11-venv", "python3.11-dev"]

[variables]
PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["python3.11 -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -U pip", "pip install -r requirements.txt"]

[start]
cmd = "bash -lc 'source /opt/venv/bin/activate && python bot.py'"
